networks:
  traductor-net:
    driver: overlay

volumes:
  mlflow-db-data:
  mlflow-artifacts-data:

services:
  app-traductor:
    image: camiloramos2000/traductor-genai:1.0.0
    ports:
      - "7860:7860"
    environment:
      - GENAI_API_KEY=${API_KEY}
      - MLFLOW_TRACKING_URI=http://mlflow-server:5000
      - GRADIO_SERVER_PORT=7860
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
      update_config:
        parallelism: 1
        delay: 10s
    networks:
      - traductor-net

  mlflow-server:
    image: ghcr.io/mlflow/mlflow:latest
    ports:
      - "5000:5000"
    command: >
      mlflow server
      --host 0.0.0.0
      --port 5000
      --backend-store-uri sqlite:///mlflow.db
      --default-artifact-root /mlflow/artifacts
      --allowed-hosts="*"
      --cors-allowed-origins="*"
    volumes:
      - mlflow-db-data:/mlflow
      - mlflow-artifacts-data:/mlflow/artifacts
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
    networks:
      - traductor-net
